/*
 * Copyright 2025 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(oscilloscope.h) */
/* BINDTOOL_HEADER_FILE_HASH(ab0875022e8e6489f13649195ee70095) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/oscilloscope/oscilloscope.h>
// pydoc.h is automatically generated in the build directory
#include <oscilloscope_pydoc.h>

void bind_oscilloscope(py::module &m) {

  using oscilloscope = ::gr::oscilloscope::oscilloscope;

  py::class_<oscilloscope, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<oscilloscope>>(m, "oscilloscope", D(oscilloscope))

      .def(py::init(&oscilloscope::make), py::arg("arg0"), py::arg("arg1"),
           py::arg("arg2"), py::arg("arg3"), py::arg("arg4"),
           D(oscilloscope, make))

      ;
}
