/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually
 * edited  */
/* The following lines can be configured to regenerate this file during cmake */
/* If manual edits are made, the following tags should be modified accordingly.
 */
/* BINDTOOL_GEN_AUTOMATIC(0) */
/* BINDTOOL_USE_PYGCCXML(0) */
/* BINDTOOL_HEADER_FILE(oscilloscope.h) */
/* BINDTOOL_HEADER_FILE_HASH(5b6da6824ea96d790ec48be37b379b70) */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/oscilloscope/oscilloscope.h>
// pydoc.h is automatically generated in the build directory
#include <oscilloscope_pydoc.h>

void bind_oscilloscope(py::module &m) {

  using oscilloscope = ::gr::oscilloscope::oscilloscope;

  py::class_<oscilloscope, gr::sync_block, gr::block, gr::basic_block,
             std::shared_ptr<oscilloscope>>(m, "oscilloscope", D(oscilloscope))

      .def(py::init(&oscilloscope::make), py::arg("ip"), py::arg("range"),
           py::arg("rate"), py::arg("duration"), py::arg("channels"),
           py::arg("type"), D(oscilloscope, make))

      .def("set_range", &oscilloscope::set_range, py::arg("range"),
           D(oscilloscope, set_range))

      .def("set_rate", &oscilloscope::set_rate, py::arg("rate"),
           D(oscilloscope, set_rate))

      .def("set_duration", &oscilloscope::set_duration, py::arg("duration"),
           D(oscilloscope, set_duration))

      .def("set_ip", &oscilloscope::set_ip, py::arg("ip"),
           D(oscilloscope, set_ip))

      .def("set_type", &oscilloscope::set_type, py::arg("type"),
           D(oscilloscope, set_type))

      ;
}
